### ISSUE TITLE
Enhancement to use multi-wallet

### ISSUE THREAD

**Issue by goking** [haw-itn/openassets-ruby#21]
## Pre-study

* When using multi wallet, it is necessary to add the file name of wallet to the URL for RPC in BitcoinCoreProvider.
* There are several implementations for specifying a wallet.
    1. An instance of `OpenAssets::Api` has an Hash object: which has the filename of the wallet as a key and has an instance of the provider for each wallet as value.
        * e.g. `api.providers["wallet001.dat"].listunspent`
    2. Make the provider a singleton and pass the filename of the wallet for each method invocation
        * e.g. `api.provider.listunspent(wallet: "wallet001.dat")`
    3. Create and hold multiple instances of `OpenAssets::Api` on the application side
        * e.g. `@apis["wallet001.dat"].provider.listunspent`

## Short-term solution

* Adopt a plan 3 that is necessary in either case
* When creating an instance of `OpenAssets::Api`, pass the file name as one of the parameters
* Add the file name of wallet to the each URL which calling RPC

After this implementation, corresponding with plan 1 or plan 2 will be made as necessary.

**Comment by azuchi** [comment]
I agree with Short-term solution.

Plan 1 and 2 have some problems. There is no problem in directly call RPC using the provider. But the behavior of `api#list_unspent` and `api.provider.listunspent` are different. In order to acquire UTXO considering asset, `api#list_unspent` is necessary, so it may be necessary to specified wallet with api.
